spring:
  datasource:
#    url:    jdbc:mysql://localhost:3307/auto_posting_test
    url: jdbc:mysql://localhost:3307/auto_posting
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

key:
  excelPath: C:\Users\Kraken\IdeaProjects\AutoPosting\src\main\resources\static\XlsxFiles\IG CLIENTS NEW SHEET gg.xlsx
  token:
  driver: C:\Users\Kraken\IdeaProjects\AutoPosting\src\main\resources\static\SeleniumWebDriver\chromedriver.exe