spring:
  datasource:
    url:    jdbc:mysql://localhost:3307/auto_posting
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect